CPU = linux
SRC_INC = ../include
SRC_LIB = ../lib
SRC_BIN = ../bin

SOMELIBS_SD_NG_NM =  -L${SRC_LIB} -leqn   -lm
SOMELIBS_SD_NG =  -L${SRC_LIB}   -lMulti -leqn   -lm
SOMELIBS_SD_JVX =  -L${SRC_LIB}  -lexpat -lMTrans -lMulti -leqn -lm ${GLOBAL_COPTS}
SOMELIBS_SD_NM_JVX =  -L${SRC_LIB} -lexpat -leqn -lm ${GLOBAL_COPTS}


CFLAGS = -O2 -I../include
#COPTS = -O2 -I${SRC_INC} -I/usr/local/include -I/usr/X11R6/include

