CPU = sun
CC = gcc
SRC_INC = ../include
SRC_LIB = ../lib
SRC_BIN = ../bin

SOMELIBS_SD_NG_NM = -L${SRC_LIB} -leqn  -lm
SOMELIBS_SD_NG =  -L${SRC_LIB}   -lMulti -leqn   -lm

CFLAGS = -O2 -I${SRC_INC} 
#COPTS = -O2 -I${SRC_INC} -I/usr/local/include -I/usr/openwin/include
#COPTS = -O2 -I${SRC_INC} -I../../include -I/usr/local/include -I/usr/X11R6/include
