document	"Document Type Definition of the JVX geometry file format."
status	"This is a release specification."
author	"Konrad Polthier"
url	"http://www.javaview.de/rsrc/jvx.dtd"
version	"1.01.00"
date	"05.04.01"
